import { canUserRunProtectedAction } from "@/lib/server/billing/gating";

import { ApiError } from "./api-error";

/**
 * Throws `ApiError("subscription_required_for_action", 402)` when the user does NOT have an
 * active-ish subscription AND the build config requires one for `routePath`.
 *
 * Generated MVPs MUST call this on every API route that the spec's
 * `capabilities.paywallGating.gatedRoutes` lists, AND MUST pass the route path
 * as the second argument so the route-aware decision in `gating.ts` kicks in:
 *
 * ```ts
 * await requireActiveSubscription(user.id, "/api/boards");
 * ```
 *
 * The `audit-paywall` audit fails the build for gated routes that don't
 * import + call this helper *with a string-literal route path that matches
 * an entry in `gatedRoutes`*. Passing only `(user.id)` is allowed for legacy
 * code (template-baked routes like settings/profile) but won't get
 * route-aware enforcement — the helper falls back to the global flag.
 *
 * Do not edit this file.
 */
export async function requireActiveSubscription(
  userId: string,
  routePath?: string
): Promise<void> {
  const allowed = await canUserRunProtectedAction(userId, routePath);
  if (!allowed) {
    throw new ApiError("subscription_required_for_action", 402);
  }
}
